class ProductAttributes {
  static final List<Map<String, dynamic>> attributes = [
    {
      "name": "1LT Evvel Sunflower Oil",
      "brand": "Evvel",
      "variant": "Sunflower Oil",
      "weight": "1LT",
      "price": "85.00 TL",
      "expiry": "2027-05-12",
    },
    {
      "name": "1LT Yesil Lefke Olive Oil",
      "brand": "Yesil Lefke",
      "variant": "Olive Oil",
      "weight": "1LT",
      "price": "420.00 TL",
      "expiry": "2027-08-20",
    },
    {
      "name": "7-Up (Lemon Lime)",
      "brand": "7-Up",
      "variant": "Soda",
      "weight": "330ml",
      "price": "28.00 TL",
      "expiry": "2026-11-15",
    },
    {
      "name": "AXE Body Spray",
      "brand": "AXE",
      "variant": "Deodorant",
      "weight": "150ml",
      "price": "145.00 TL",
      "expiry": "2028-02-01",
    },
    {
      "name": "Akdeniz",
      "brand": "Akdeniz",
      "variant": "Canned Goods",
      "weight": "400g",
      "price": "35.00 TL",
      "expiry": "2027-04-10",
    },
    {
      "name": "Akdeniz Chopped Tomatoes (Doğranmiş Domates)",
      "brand": "Akdeniz",
      "variant": "Tomatoes",
      "weight": "400g",
      "price": "32.00 TL",
      "expiry": "2027-09-22",
    },
    {
      "name": "Akdeniz Doğranmiş Domates (Chopped Tomatoes)",
      "brand": "Akdeniz",
      "variant": "Tomatoes",
      "weight": "400g",
      "price": "32.00 TL",
      "expiry": "2027-09-22",
    },
    {
      "name": "Akdeniz Sweet Corn (Tatli Misir)",
      "brand": "Akdeniz",
      "variant": "Corn",
      "weight": "340g",
      "price": "45.00 TL",
      "expiry": "2027-12-01",
    },
    {
      "name": "Akdeniz Ton Baliği",
      "brand": "Akdeniz",
      "variant": "Tuna",
      "weight": "160g",
      "price": "95.00 TL",
      "expiry": "2028-03-15",
    },
    {
      "name": "Amsterdam Navigator",
      "brand": "Amsterdam",
      "variant": "Beverage",
      "weight": "500ml",
      "price": "85.00 TL",
      "expiry": "2026-10-30",
    },
    {
      "name": "Ari Grissini Kepekli (Whole Wheat)",
      "brand": "Ari",
      "variant": "Grissini",
      "weight": "125g",
      "price": "24.00 TL",
      "expiry": "2026-08-20",
    },
    {
      "name": "Ari Grissini Misirli (Corn)",
      "brand": "Ari",
      "variant": "Grissini",
      "weight": "125g",
      "price": "24.00 TL",
      "expiry": "2026-08-22",
    },
    {
      "name": "Ari Grissini Sade (Plain)",
      "brand": "Ari",
      "variant": "Grissini",
      "weight": "125g",
      "price": "22.00 TL",
      "expiry": "2026-08-18",
    },
    {
      "name": "Ari Grissini Susamli (Sesame)",
      "brand": "Ari",
      "variant": "Grissini",
      "weight": "125g",
      "price": "26.00 TL",
      "expiry": "2026-08-25",
    },
    {
      "name": "Asli Su Spring Water",
      "brand": "Asli Su",
      "variant": "Water",
      "weight": "500ml",
      "price": "20.00 TL",
      "expiry": "2026-07-01",
    },
    {
      "name": "Avocados",
      "brand": "Produce",
      "variant": "Fruit",
      "weight": "Piece",
      "price": "55.00 TL",
      "expiry": "N/A",
    },
    {
      "name": "Bag of Lemon",
      "brand": "Produce",
      "variant": "Fruit",
      "weight": "500g",
      "price": "40.00 TL",
      "expiry": "N/A",
    },
    {
      "name": "Bag of Oranges",
      "brand": "Produce",
      "variant": "Fruit",
      "weight": "2kg",
      "price": "75.00 TL",
      "expiry": "N/A",
    },
    {
      "name": "Ballet butter blend",
      "brand": "Ballet",
      "variant": "Butter",
      "weight": "250g",
      "price": "65.00 TL",
      "expiry": "2026-12-01",
    },
    {
      "name": "Balik Kraker (Plain)",
      "brand": "ETİ",
      "variant": "Cracker",
      "weight": "40g",
      "price": "20.00 TL",
      "expiry": "2026-09-10",
    },
    {
      "name": "Balik Kraker (Spicy)",
      "brand": "ETİ",
      "variant": "Cracker",
      "weight": "40g",
      "price": "20.00 TL",
      "expiry": "2026-09-15",
    },
    {
      "name": "Bananas",
      "brand": "Produce",
      "variant": "Fruit",
      "weight": "1kg",
      "price": "85.00 TL",
      "expiry": "N/A",
    },
    {
      "name": "Beypazari",
      "brand": "Beypazari",
      "variant": "Mineral Water",
      "weight": "200ml",
      "price": "20.00 TL",
      "expiry": "2027-05-01",
    },
    {
      "name": "Beypazari Limon Aromali Maden Suyu (Lemon Mineral Water)",
      "brand": "Beypazari",
      "variant": "Mineral Water",
      "weight": "200ml",
      "price": "22.00 TL",
      "expiry": "2027-06-12",
    },
    {
      "name": "Beypazari Vişne Aromali Sour Cherry Mineral Water",
      "brand": "Beypazari",
      "variant": "Mineral Water",
      "weight": "200ml",
      "price": "22.00 TL",
      "expiry": "2027-06-15",
    },
    {
      "name": "Beypazari Çilek (Strawberry Mineral Water)",
      "brand": "Beypazari",
      "variant": "Mineral Water",
      "weight": "200ml",
      "price": "22.00 TL",
      "expiry": "2027-06-20",
    },
    {
      "name": "Bidolu",
      "brand": "Ülker",
      "variant": "Wafer",
      "weight": "81g",
      "price": "35.00 TL",
      "expiry": "2026-12-05",
    },
    {
      "name": "Biscolata",
      "brand": "Biscolata",
      "variant": "Chocolate",
      "weight": "100g",
      "price": "45.00 TL",
      "expiry": "2027-01-10",
    },
    {
      "name": "Biscolata Cups",
      "brand": "Biscolata",
      "variant": "Chocolate Cups",
      "weight": "115g",
      "price": "52.00 TL",
      "expiry": "2027-01-15",
    },
    {
      "name": "Bran Flakes",
      "brand": "Kellogg's",
      "variant": "Cereal",
      "weight": "500g",
      "price": "110.00 TL",
      "expiry": "2027-08-01",
    },
    {
      "name": "Breaks (Chocolate)",
      "brand": "Torku",
      "variant": "Biscuit",
      "weight": "140g",
      "price": "38.00 TL",
      "expiry": "2026-11-30",
    },
    {
      "name": "Breamore Croissants",
      "brand": "Breamore",
      "variant": "Bakery",
      "weight": "50g",
      "price": "25.00 TL",
      "expiry": "2026-05-20",
    },
    {
      "name": "Bubble Up",
      "brand": "Bubble Up",
      "variant": "Soda",
      "weight": "330ml",
      "price": "24.00 TL",
      "expiry": "2027-02-10",
    },
    {
      "name": "Burçak Yulafli",
      "brand": "ETİ",
      "variant": "Biscuit",
      "weight": "125g",
      "price": "30.00 TL",
      "expiry": "2026-10-15",
    },
    {
      "name": "Burçak Yulafli (Oat)",
      "brand": "ETİ",
      "variant": "Biscuit",
      "weight": "125g",
      "price": "30.00 TL",
      "expiry": "2026-10-15",
    },
    {
      "name": "Cabbage",
      "brand": "Produce",
      "variant": "Vegetable",
      "weight": "1kg",
      "price": "45.00 TL",
      "expiry": "N/A",
    },
    {
      "name": "Calvé Mayonez (Mayonnaise)",
      "brand": "Calvé",
      "variant": "Mayonnaise",
      "weight": "540g",
      "price": "125.00 TL",
      "expiry": "2026-12-01",
    },
    {
      "name": "Calvé Burger Sos",
      "brand": "Calvé",
      "variant": "Sauce",
      "weight": "250ml",
      "price": "85.00 TL",
      "expiry": "2027-01-15",
    },
    {
      "name": "Calvé Hardal (Mustard)",
      "brand": "Calvé",
      "variant": "Mustard",
      "weight": "250ml",
      "price": "75.00 TL",
      "expiry": "2027-03-10",
    },
    {
      "name": "Calvé Ketchup",
      "brand": "Calvé",
      "variant": "Ketchup",
      "weight": "600g",
      "price": "95.00 TL",
      "expiry": "2027-04-01",
    },
    {
      "name": "Calvé Ketchup (small)",
      "brand": "Calvé",
      "variant": "Ketchup",
      "weight": "250g",
      "price": "55.00 TL",
      "expiry": "2027-04-01",
    },
    {
      "name": "Calvé Mayonez (small)",
      "brand": "Calvé",
      "variant": "Mayonnaise",
      "weight": "250g",
      "price": "65.00 TL",
      "expiry": "2026-12-01",
    },
    {
      "name": "Cappy Karişik (Mixed Fruit)",
      "brand": "Cappy",
      "variant": "Juice",
      "weight": "1LT",
      "price": "48.00 TL",
      "expiry": "2027-02-25",
    },
    {
      "name": "Cappy Vişne (Sour Cherry)",
      "brand": "Cappy",
      "variant": "Juice",
      "weight": "1LT",
      "price": "48.00 TL",
      "expiry": "2027-02-25",
    },
    {
      "name": "Cappy Şeftali (Peach)",
      "brand": "Cappy",
      "variant": "Juice",
      "weight": "1LT",
      "price": "48.00 TL",
      "expiry": "2027-02-25",
    },
    {
      "name": "Capri-Sun",
      "brand": "Capri-Sun",
      "variant": "Juice",
      "weight": "200ml",
      "price": "22.00 TL",
      "expiry": "2027-01-10",
    },
    {
      "name": "Caramel Wafers",
      "brand": "Tunnock's",
      "variant": "Wafer",
      "weight": "30g",
      "price": "25.00 TL",
      "expiry": "2026-12-20",
    },
    {
      "name": "Cauliflower",
      "brand": "Produce",
      "variant": "Vegetable",
      "weight": "1kg",
      "price": "60.00 TL",
      "expiry": "N/A",
    },
    {
      "name": "Chocolate wafer",
      "brand": "Generic",
      "variant": "Wafer",
      "weight": "40g",
      "price": "20.00 TL",
      "expiry": "2026-10-30",
    },
    {
      "name": "Chupa Chups Assorted Lollipops",
      "brand": "Chupa Chups",
      "variant": "Candy",
      "weight": "12g",
      "price": "20.00 TL",
      "expiry": "2028-01-01",
    },
    {
      "name": "Chupa Chups Melody Pops",
      "brand": "Chupa Chups",
      "variant": "Candy",
      "weight": "15g",
      "price": "25.00 TL",
      "expiry": "2028-01-01",
    },
    {
      "name": "Cin (Orange)",
      "brand": "ETİ",
      "variant": "Biscuit",
      "weight": "25g",
      "price": "20.00 TL",
      "expiry": "2026-11-15",
    },
    {
      "name": "Cin Çilekli (Strawberry)",
      "brand": "ETİ",
      "variant": "Biscuit",
      "weight": "25g",
      "price": "20.00 TL",
      "expiry": "2026-11-15",
    },
    {
      "name": "Coca'cola Zero Sugar",
      "brand": "Coca-Cola",
      "variant": "Soda",
      "weight": "330ml",
      "price": "30.00 TL",
      "expiry": "2027-02-20",
    },
    {
      "name": "Coca-Cola Original Taste",
      "brand": "Coca-Cola",
      "variant": "Soda",
      "weight": "330ml",
      "price": "30.00 TL",
      "expiry": "2027-02-20",
    },
    {
      "name": "Coca-Cola Original",
      "brand": "Coca-Cola",
      "variant": "Soda",
      "weight": "1LT",
      "price": "45.00 TL",
      "expiry": "2027-02-20",
    },
    {
      "name": "Coca-Cola Zero Sugar",
      "brand": "Coca-Cola",
      "variant": "Soda",
      "weight": "1LT",
      "price": "45.00 TL",
      "expiry": "2027-02-20",
    },
    {
      "name": "Crax (Spicy/Cheese)",
      "brand": "ETİ",
      "variant": "Stick",
      "weight": "50g",
      "price": "22.00 TL",
      "expiry": "2026-12-10",
    },
    {
      "name": "Crax Stick Crackers",
      "brand": "ETİ",
      "variant": "Stick",
      "weight": "50g",
      "price": "20.00 TL",
      "expiry": "2026-12-10",
    },
    {
      "name": "Cream Crackers",
      "brand": "Jacob's",
      "variant": "Cracker",
      "weight": "200g",
      "price": "55.00 TL",
      "expiry": "2027-03-01",
    },
    {
      "name": "Crush Orange Soda",
      "brand": "Crush",
      "variant": "Soda",
      "weight": "330ml",
      "price": "25.00 TL",
      "expiry": "2027-01-15",
    },
    {
      "name": "Dardanel Ton Baliği",
      "brand": "Dardanel",
      "variant": "Tuna",
      "weight": "2x160g",
      "price": "185.00 TL",
      "expiry": "2028-10-10",
    },
    {
      "name": "Dark Blue Energy Drink",
      "brand": "Dark Blue",
      "variant": "Energy",
      "weight": "250ml",
      "price": "45.00 TL",
      "expiry": "2027-05-10",
    },
    {
      "name": "Didi",
      "brand": "Didi",
      "variant": "Iced Tea",
      "weight": "500ml",
      "price": "30.00 TL",
      "expiry": "2027-01-30",
    },
    {
      "name": "Didi Iced Tea (Bottles)",
      "brand": "Didi",
      "variant": "Iced Tea",
      "weight": "1LT",
      "price": "45.00 TL",
      "expiry": "2027-01-30",
    },
    {
      "name": "Dimes Cool Berry Mix",
      "brand": "Dimes",
      "variant": "Concentrate",
      "weight": "310ml",
      "price": "95.00 TL",
      "expiry": "2027-04-12",
    },
    {
      "name": "Dimes Cool Karpuz (Watermelon) Mix",
      "brand": "Dimes",
      "variant": "Concentrate",
      "weight": "310ml",
      "price": "95.00 TL",
      "expiry": "2027-04-12",
    },
    {
      "name": "Dimes Cool Lime Mix",
      "brand": "Dimes",
      "variant": "Concentrate",
      "weight": "310ml",
      "price": "95.00 TL",
      "expiry": "2027-04-12",
    },
    {
      "name": "Dimes Cool Mango Mix",
      "brand": "Dimes",
      "variant": "Concentrate",
      "weight": "310ml",
      "price": "95.00 TL",
      "expiry": "2027-04-12",
    },
    {
      "name": "Dolu",
      "brand": "Ülker",
      "variant": "Wafer",
      "weight": "30g",
      "price": "20.00 TL",
      "expiry": "2026-11-20",
    },
    {
      "name": "Dudomi Noodles",
      "brand": "Dudomi",
      "variant": "Noodles",
      "weight": "70g",
      "price": "22.00 TL",
      "expiry": "2027-03-15",
    },
    {
      "name": "Ecolive Virgin Olive Oil",
      "brand": "Ecolive",
      "variant": "Olive Oil",
      "weight": "1LT",
      "price": "450.00 TL",
      "expiry": "2027-10-01",
    },
    {
      "name": "Eggplants (Purple)",
      "brand": "Produce",
      "variant": "Vegetable",
      "weight": "1kg",
      "price": "55.00 TL",
      "expiry": "N/A",
    },
    {
      "name": "Enjoy Cat Food (Chicken/Vegetable)",
      "brand": "Enjoy",
      "variant": "Cat Food",
      "weight": "1.5kg",
      "price": "280.00 TL",
      "expiry": "2028-01-10",
    },
    {
      "name": "Enjoy Cat Food (Gourmet Paté Cans)",
      "brand": "Enjoy",
      "variant": "Cat Food",
      "weight": "400g",
      "price": "65.00 TL",
      "expiry": "2028-05-20",
    },
    {
      "name": "Enjoy Cat Food (Gourmet Paté)",
      "brand": "Enjoy",
      "variant": "Cat Food",
      "weight": "100g",
      "price": "35.00 TL",
      "expiry": "2028-05-20",
    },
    {
      "name": "Enjoy Dog Food (Beef/High Energy)",
      "brand": "Enjoy",
      "variant": "Dog Food",
      "weight": "2.5kg",
      "price": "450.00 TL",
      "expiry": "2028-01-15",
    },
    {
      "name": "Erikli Su",
      "brand": "Erikli",
      "variant": "Water",
      "weight": "500ml",
      "price": "20.00 TL",
      "expiry": "2026-09-01",
    },
    {
      "name": "Etimek (Original)",
      "brand": "ETİ",
      "variant": "Rusk",
      "weight": "143g",
      "price": "35.00 TL",
      "expiry": "2027-02-10",
    },
    {
      "name": "Etimek (Whole Wheat)",
      "brand": "ETİ",
      "variant": "Rusk",
      "weight": "143g",
      "price": "38.00 TL",
      "expiry": "2027-02-10",
    },
    {
      "name": "Evvel sunflower 3L",
      "brand": "Evvel",
      "variant": "Sunflower Oil",
      "weight": "3LT",
      "price": "260.00 TL",
      "expiry": "2027-06-30",
    },
    {
      "name": "Fanta",
      "brand": "Fanta",
      "variant": "Soda",
      "weight": "330ml",
      "price": "28.00 TL",
      "expiry": "2027-03-01",
    },
    {
      "name": "Fanta Orange",
      "brand": "Fanta",
      "variant": "Soda",
      "weight": "1LT",
      "price": "42.00 TL",
      "expiry": "2027-03-01",
    },
    {
      "name": "Form (Rice Cakes)",
      "brand": "ETİ",
      "variant": "Rice Cake",
      "weight": "45g",
      "price": "25.00 TL",
      "expiry": "2026-12-20",
    },
    {
      "name": "Form (Whole Wheat Biscuit)",
      "brand": "ETİ",
      "variant": "Biscuit",
      "weight": "45g",
      "price": "22.00 TL",
      "expiry": "2026-12-20",
    },
    {
      "name": "Fruit & Fibre",
      "brand": "Kellogg's",
      "variant": "Cereal",
      "weight": "500g",
      "price": "140.00 TL",
      "expiry": "2027-07-15",
    },
    {
      "name": "Fruit (Miko) Pink Grapefruit",
      "brand": "Miko",
      "variant": "Juice",
      "weight": "1LT",
      "price": "55.00 TL",
      "expiry": "2027-01-10",
    },
    {
      "name": "Frutti",
      "brand": "Uludağ",
      "variant": "Mineral Water",
      "weight": "200ml",
      "price": "22.00 TL",
      "expiry": "2027-04-01",
    },
    {
      "name": "Frutti Orman Meyveli (Mixed Berries)",
      "brand": "Uludağ",
      "variant": "Mineral Water",
      "weight": "200ml",
      "price": "22.00 TL",
      "expiry": "2027-04-01",
    },
    {
      "name": "Fuse Tea Mango & Pineapple",
      "brand": "Fuse Tea",
      "variant": "Iced Tea",
      "weight": "500ml",
      "price": "30.00 TL",
      "expiry": "2027-02-28",
    },
    {
      "name": "Fuse Tea Watermelon",
      "brand": "Fuse Tea",
      "variant": "Iced Tea",
      "weight": "500ml",
      "price": "30.00 TL",
      "expiry": "2027-02-28",
    },
    {
      "name": "Garlic",
      "brand": "Produce",
      "variant": "Vegetable",
      "weight": "200g",
      "price": "45.00 TL",
      "expiry": "N/A",
    },
    {
      "name": "Ginger",
      "brand": "Produce",
      "variant": "Vegetable",
      "weight": "100g",
      "price": "50.00 TL",
      "expiry": "N/A",
    },
    {
      "name": "Ginger Nuts",
      "brand": "McVitie's",
      "variant": "Biscuit",
      "weight": "250g",
      "price": "65.00 TL",
      "expiry": "2027-03-10",
    },
    {
      "name": "Gong (Corn/Rice Cake)",
      "brand": "ETİ",
      "variant": "Snack",
      "weight": "64g",
      "price": "28.00 TL",
      "expiry": "2026-12-05",
    },
    {
      "name": "Gong Pops (Spicy)",
      "brand": "ETİ",
      "variant": "Snack",
      "weight": "80g",
      "price": "35.00 TL",
      "expiry": "2026-12-10",
    },
    {
      "name": "Green Chilies / Peppers (Long)",
      "brand": "Produce",
      "variant": "Vegetable",
      "weight": "500g",
      "price": "40.00 TL",
      "expiry": "N/A",
    },
    {
      "name": "Green Cucumbers",
      "brand": "Produce",
      "variant": "Vegetable",
      "weight": "1kg",
      "price": "35.00 TL",
      "expiry": "N/A",
    },
    {
      "name": "Gulgun Sut",
      "brand": "Gülgün",
      "variant": "Milk",
      "weight": "1LT",
      "price": "45.00 TL",
      "expiry": "2026-05-30",
    },
    {
      "name": "Gullón Zero",
      "brand": "Gullón",
      "variant": "Biscuit",
      "weight": "200g",
      "price": "85.00 TL",
      "expiry": "2027-06-01",
    },
    {
      "name": "Gullón Zero biscuits",
      "brand": "Gullón",
      "variant": "Biscuit",
      "weight": "170g",
      "price": "80.00 TL",
      "expiry": "2027-06-01",
    },
    {
      "name": "Gustotevia Maggi",
      "brand": "Maggi",
      "variant": "Seasoning",
      "weight": "200g",
      "price": "55.00 TL",
      "expiry": "2027-11-20",
    },
    {
      "name": "Heinz Beanz (Baked Beans in Tomato Sauce)",
      "brand": "Heinz",
      "variant": "Beans",
      "weight": "415g",
      "price": "65.00 TL",
      "expiry": "2028-02-10",
    },
    {
      "name": "Heinz Classic BBQ Sauce",
      "brand": "Heinz",
      "variant": "Sauce",
      "weight": "480g",
      "price": "110.00 TL",
      "expiry": "2027-09-01",
    },
    {
      "name": "Heinz Garlic Mayonnaise",
      "brand": "Heinz",
      "variant": "Sauce",
      "weight": "400ml",
      "price": "135.00 TL",
      "expiry": "2027-05-15",
    },
    {
      "name": "Heinz Creamy Mayonnaise",
      "brand": "Heinz",
      "variant": "Sauce",
      "weight": "400ml",
      "price": "135.00 TL",
      "expiry": "2027-05-15",
    },
    {
      "name": "Heinz Sweet Corn",
      "brand": "Heinz",
      "variant": "Corn",
      "weight": "340g",
      "price": "65.00 TL",
      "expiry": "2028-01-20",
    },
    {
      "name": "Heinz Tomato Ketchup (Small)",
      "brand": "Heinz",
      "variant": "Ketchup",
      "weight": "250g",
      "price": "75.00 TL",
      "expiry": "2027-08-30",
    },
    {
      "name": "Hoşbeş",
      "brand": "ETİ",
      "variant": "Wafer",
      "weight": "70g",
      "price": "30.00 TL",
      "expiry": "2026-12-15",
    },
    {
      "name": "Hoşbeş (Wafer)",
      "brand": "ETİ",
      "variant": "Wafer",
      "weight": "70g",
      "price": "30.00 TL",
      "expiry": "2026-12-15",
    },
    {
      "name": "Juss Coco (Coconut & Pineapple)",
      "brand": "Juss",
      "variant": "Juice",
      "weight": "1LT",
      "price": "52.00 TL",
      "expiry": "2027-03-10",
    },
    {
      "name": "Juss Peach Nectar",
      "brand": "Juss",
      "variant": "Juice",
      "weight": "1LT",
      "price": "45.00 TL",
      "expiry": "2027-03-10",
    },
    {
      "name": "Juss Pear or Green Apple",
      "brand": "Juss",
      "variant": "Juice",
      "weight": "1LT",
      "price": "45.00 TL",
      "expiry": "2027-03-10",
    },
    {
      "name": "Juss Pomegranate",
      "brand": "Juss",
      "variant": "Juice",
      "weight": "1LT",
      "price": "48.00 TL",
      "expiry": "2027-03-10",
    },
    {
      "name": "Juss Apple",
      "brand": "Juss",
      "variant": "Juice",
      "weight": "1LT",
      "price": "42.00 TL",
      "expiry": "2027-03-10",
    },
    {
      "name": "Juss Black Grape",
      "brand": "Juss",
      "variant": "Juice",
      "weight": "1LT",
      "price": "48.00 TL",
      "expiry": "2027-03-10",
    },
    {
      "name": "Juss Coconut",
      "brand": "Juss",
      "variant": "Juice",
      "weight": "1LT",
      "price": "52.00 TL",
      "expiry": "2027-03-10",
    },
    {
      "name": "Juss Kayisi (Apricot)",
      "brand": "Juss",
      "variant": "Juice",
      "weight": "1LT",
      "price": "45.00 TL",
      "expiry": "2027-03-10",
    },
    {
      "name": "Juss Mango",
      "brand": "Juss",
      "variant": "Juice",
      "weight": "1LT",
      "price": "48.00 TL",
      "expiry": "2027-03-10",
    },
    {
      "name": "Juss Mixed Fruit",
      "brand": "Juss",
      "variant": "Juice",
      "weight": "1LT",
      "price": "45.00 TL",
      "expiry": "2027-03-10",
    },
    {
      "name": "Juss Peach",
      "brand": "Juss",
      "variant": "Juice",
      "weight": "1LT",
      "price": "45.00 TL",
      "expiry": "2027-03-10",
    },
    {
      "name": "Juss Pear",
      "brand": "Juss",
      "variant": "Juice",
      "weight": "1LT",
      "price": "45.00 TL",
      "expiry": "2027-03-10",
    },
    {
      "name": "Juss Pineapple",
      "brand": "Juss",
      "variant": "Juice",
      "weight": "1LT",
      "price": "48.00 TL",
      "expiry": "2027-03-10",
    },
    {
      "name": "Juss Pineapple Flavor",
      "brand": "Juss",
      "variant": "Juice",
      "weight": "1LT",
      "price": "48.00 TL",
      "expiry": "2027-03-10",
    },
    {
      "name": "Juss Portakal",
      "brand": "Juss",
      "variant": "Juice",
      "weight": "1LT",
      "price": "45.00 TL",
      "expiry": "2027-03-10",
    },
    {
      "name": "Juss Sour Cherry",
      "brand": "Juss",
      "variant": "Juice",
      "weight": "1LT",
      "price": "48.00 TL",
      "expiry": "2027-03-10",
    },
    {
      "name": "Juss Strawberry",
      "brand": "Juss",
      "variant": "Juice",
      "weight": "1LT",
      "price": "48.00 TL",
      "expiry": "2027-03-10",
    },
    {
      "name": "Juss Tropical/Mixed Fruit",
      "brand": "Juss",
      "variant": "Juice",
      "weight": "1LT",
      "price": "45.00 TL",
      "expiry": "2027-03-10",
    },
    {
      "name": "Juss Tropikal",
      "brand": "Juss",
      "variant": "Juice",
      "weight": "1LT",
      "price": "45.00 TL",
      "expiry": "2027-03-10",
    },
    {
      "name": "Juss Vişne (Sour Cherry)",
      "brand": "Juss",
      "variant": "Juice",
      "weight": "1LT",
      "price": "48.00 TL",
      "expiry": "2027-03-10",
    },
    {
      "name": "KOOP Portakal Suyu (Orange Juice)",
      "brand": "KOOP",
      "variant": "Juice",
      "weight": "1LT",
      "price": "48.00 TL",
      "expiry": "2026-12-20",
    },
    {
      "name": "Kakaolu Bisküvi",
      "brand": "Ülker",
      "variant": "Biscuit",
      "weight": "125g",
      "price": "28.00 TL",
      "expiry": "2026-11-05",
    },
    {
      "name": "Karuzo Custard & Strawberry",
      "brand": "Karuzo",
      "variant": "Bakery",
      "weight": "60g",
      "price": "32.00 TL",
      "expiry": "2026-06-15",
    },
    {
      "name": "Karuzo Pistachio Cream",
      "brand": "Karuzo",
      "variant": "Bakery",
      "weight": "60g",
      "price": "35.00 TL",
      "expiry": "2026-06-15",
    },
    {
      "name": "Karuzo Chocolate Croissant",
      "brand": "Karuzo",
      "variant": "Bakery",
      "weight": "60g",
      "price": "30.00 TL",
      "expiry": "2026-06-15",
    },
    {
      "name": "Karuzo Vanilla & Blueberry",
      "brand": "Karuzo",
      "variant": "Bakery",
      "weight": "60g",
      "price": "32.00 TL",
      "expiry": "2026-06-15",
    },
    {
      "name": "Kellogg's Coco Pops",
      "brand": "Kellogg's",
      "variant": "Cereal",
      "weight": "500g",
      "price": "115.00 TL",
      "expiry": "2027-07-20",
    },
    {
      "name": "Kellogg's Corn Flakes (Bag)",
      "brand": "Kellogg's",
      "variant": "Cereal",
      "weight": "1kg",
      "price": "140.00 TL",
      "expiry": "2027-07-20",
    },
    {
      "name": "Kellogg's Corn Flakes (Big Pack)",
      "brand": "Kellogg's",
      "variant": "Cereal",
      "weight": "750g",
      "price": "125.00 TL",
      "expiry": "2027-07-20",
    },
    {
      "name": "Kellogg's Crunches",
      "brand": "Kellogg's",
      "variant": "Cereal",
      "weight": "400g",
      "price": "110.00 TL",
      "expiry": "2027-07-20",
    },
    {
      "name": "Kellogg's Frosties",
      "brand": "Kellogg's",
      "variant": "Cereal",
      "weight": "500g",
      "price": "120.00 TL",
      "expiry": "2027-07-20",
    },
    {
      "name": "Kellogg's Honey Loops",
      "brand": "Kellogg's",
      "variant": "Cereal",
      "weight": "375g",
      "price": "115.00 TL",
      "expiry": "2027-07-20",
    },
    {
      "name": "Kellogg's Krave Choco Nut",
      "brand": "Kellogg's",
      "variant": "Cereal",
      "weight": "375g",
      "price": "130.00 TL",
      "expiry": "2027-07-20",
    },
    {
      "name": "Kellogg's oaties",
      "brand": "Kellogg's",
      "variant": "Cereal",
      "weight": "400g",
      "price": "105.00 TL",
      "expiry": "2027-07-20",
    },
    {
      "name": "Kurabi",
      "brand": "Ülker",
      "variant": "Cookie",
      "weight": "150g",
      "price": "55.00 TL",
      "expiry": "2026-10-30",
    },
    {
      "name": "Kurabi (Cocoa Cookie)",
      "brand": "Ülker",
      "variant": "Cookie",
      "weight": "150g",
      "price": "55.00 TL",
      "expiry": "2026-10-30",
    },
    {
      "name": "Lemons",
      "brand": "Produce",
      "variant": "Fruit",
      "weight": "1kg",
      "price": "45.00 TL",
      "expiry": "N/A",
    },
    {
      "name": "Lyons Rich Tea Digestive",
      "brand": "Lyons",
      "variant": "Biscuit",
      "weight": "300g",
      "price": "65.00 TL",
      "expiry": "2027-04-05",
    },
    {
      "name": "M'vities Digestive / Biscuits",
      "brand": "McVitie's",
      "variant": "Biscuit",
      "weight": "250g",
      "price": "70.00 TL",
      "expiry": "2027-04-10",
    },
    {
      "name": "Mardo Lemon",
      "brand": "Mardo",
      "variant": "Beverage",
      "weight": "330ml",
      "price": "35.00 TL",
      "expiry": "2026-09-15",
    },
    {
      "name": "Maresi Bruschette Chips",
      "brand": "Maresi",
      "variant": "Snack",
      "weight": "70g",
      "price": "48.00 TL",
      "expiry": "2026-12-25",
    },
    {
      "name": "Maryland Choc Chip Cookies",
      "brand": "Maryland",
      "variant": "Biscuit",
      "weight": "200g",
      "price": "85.00 TL",
      "expiry": "2027-02-14",
    },
    {
      "name": "McVitie's Digestive",
      "brand": "McVitie's",
      "variant": "Biscuit",
      "weight": "250g",
      "price": "70.00 TL",
      "expiry": "2027-04-10",
    },
    {
      "name": "Mey Su",
      "brand": "Mey Su",
      "variant": "Juice",
      "weight": "1LT",
      "price": "42.00 TL",
      "expiry": "2026-11-20",
    },
    {
      "name": "Monster Energy Drink",
      "brand": "Monster",
      "variant": "Energy",
      "weight": "500ml",
      "price": "75.00 TL",
      "expiry": "2027-10-15",
    },
    {
      "name": "Mr. Brown Coffee",
      "brand": "Mr. Brown",
      "variant": "Coffee",
      "weight": "240ml",
      "price": "55.00 TL",
      "expiry": "2026-11-01",
    },
    {
      "name": "Nescafe Classic",
      "brand": "Nescafe",
      "variant": "Coffee",
      "weight": "200g",
      "price": "180.00 TL",
      "expiry": "2028-05-10",
    },
    {
      "name": "Nesfit Yulafli",
      "brand": "Nestle",
      "variant": "Cereal",
      "weight": "400g",
      "price": "95.00 TL",
      "expiry": "2027-08-30",
    },
    {
      "name": "Nutymax (Hazelnut)",
      "brand": "Şölen",
      "variant": "Chocolate",
      "weight": "44g",
      "price": "28.00 TL",
      "expiry": "2026-12-15",
    },
    {
      "name": "Nutymax (Pistachio)",
      "brand": "Şölen",
      "variant": "Chocolate",
      "weight": "44g",
      "price": "35.00 TL",
      "expiry": "2026-12-15",
    },
    {
      "name": "Onions (purple)",
      "brand": "Produce",
      "variant": "Vegetable",
      "weight": "1kg",
      "price": "35.00 TL",
      "expiry": "N/A",
    },
    {
      "name": "Onions (white)",
      "brand": "Produce",
      "variant": "Vegetable",
      "weight": "1kg",
      "price": "30.00 TL",
      "expiry": "N/A",
    },
    {
      "name": "Oranges",
      "brand": "Produce",
      "variant": "Fruit",
      "weight": "1kg",
      "price": "45.00 TL",
      "expiry": "N/A",
    },
    {
      "name": "Oreo O's",
      "brand": "Post",
      "variant": "Cereal",
      "weight": "350g",
      "price": "165.00 TL",
      "expiry": "2027-06-10",
    },
    {
      "name": "PIN Cool Lime (Tea Drink)",
      "brand": "PIN",
      "variant": "Iced Tea",
      "weight": "250ml",
      "price": "45.00 TL",
      "expiry": "2027-02-15",
    },
    {
      "name": "PIN Hibiscus Tea",
      "brand": "PIN",
      "variant": "Iced Tea",
      "weight": "250ml",
      "price": "45.00 TL",
      "expiry": "2027-02-15",
    },
    {
      "name": "Paykek biscuit",
      "brand": "ETİ",
      "variant": "Cake",
      "weight": "40g",
      "price": "25.00 TL",
      "expiry": "2026-05-30",
    },
    {
      "name": "Peak Milk Powder",
      "brand": "Peak",
      "variant": "Milk Powder",
      "weight": "400g",
      "price": "195.00 TL",
      "expiry": "2028-01-01",
    },
    {
      "name": "Pepsi",
      "brand": "Pepsi",
      "variant": "Soda",
      "weight": "330ml",
      "price": "28.00 TL",
      "expiry": "2027-04-10",
    },
    {
      "name": "Pepsi Blue",
      "brand": "Pepsi",
      "variant": "Soda",
      "weight": "330ml",
      "price": "35.00 TL",
      "expiry": "2027-04-10",
    },
    {
      "name": "Pepsi Classic",
      "brand": "Pepsi",
      "variant": "Soda",
      "weight": "1LT",
      "price": "45.00 TL",
      "expiry": "2027-04-10",
    },
    {
      "name": "Pepsi Max Zero Sugar",
      "brand": "Pepsi",
      "variant": "Soda",
      "weight": "1LT",
      "price": "45.00 TL",
      "expiry": "2027-04-10",
    },
    {
      "name": "Pepsi Regular",
      "brand": "Pepsi",
      "variant": "Soda",
      "weight": "2.5LT",
      "price": "85.00 TL",
      "expiry": "2027-04-10",
    },
    {
      "name": "Petit Beurre",
      "brand": "Ülker",
      "variant": "Biscuit",
      "weight": "450g",
      "price": "85.00 TL",
      "expiry": "2027-02-28",
    },
    {
      "name": "Peyman Bahçeden Soslu Yer Fistiği (Sauced Peanuts)",
      "brand": "Peyman",
      "variant": "Nuts",
      "weight": "180g",
      "price": "65.00 TL",
      "expiry": "2027-03-10",
    },
    {
      "name": "Peyman Bahçeden Çiğ Kabak Çekirdeği (Raw Pumpkin Seeds)",
      "brand": "Peyman",
      "variant": "Nuts",
      "weight": "150g",
      "price": "75.00 TL",
      "expiry": "2027-03-10",
    },
    {
      "name": "Peyman: Bahçeden Çiğ Kabak Çekirdeği (Raw Pumpkin Seeds)",
      "brand": "Peyman",
      "variant": "Nuts",
      "weight": "150g",
      "price": "75.00 TL",
      "expiry": "2027-03-10",
    },
    {
      "name": "Popkek Banana",
      "brand": "ETİ",
      "variant": "Cake",
      "weight": "45g",
      "price": "22.00 TL",
      "expiry": "2026-06-01",
    },
    {
      "name": "Popkek Lemon",
      "brand": "ETİ",
      "variant": "Cake",
      "weight": "45g",
      "price": "22.00 TL",
      "expiry": "2026-06-01",
    },
    {
      "name": "Popkek choco",
      "brand": "ETİ",
      "variant": "Cake",
      "weight": "45g",
      "price": "22.00 TL",
      "expiry": "2026-06-01",
    },
    {
      "name": "Popz Microwave Popcorn (Butter)",
      "brand": "Popz",
      "variant": "Popcorn",
      "weight": "100g",
      "price": "45.00 TL",
      "expiry": "2027-10-30",
    },
    {
      "name": "Potatoes",
      "brand": "Produce",
      "variant": "Vegetable",
      "weight": "1kg",
      "price": "25.00 TL",
      "expiry": "N/A",
    },
    {
      "name": "Red Apples",
      "brand": "Produce",
      "variant": "Fruit",
      "weight": "1kg",
      "price": "55.00 TL",
      "expiry": "N/A",
    },
    {
      "name": "Red Bell Peppers",
      "brand": "Produce",
      "variant": "Vegetable",
      "weight": "500g",
      "price": "50.00 TL",
      "expiry": "N/A",
    },
    {
      "name": "Red Bull",
      "brand": "Red Bull",
      "variant": "Energy",
      "weight": "250ml",
      "price": "65.00 TL",
      "expiry": "2027-11-20",
    },
    {
      "name": "Red Tomatoes",
      "brand": "Produce",
      "variant": "Vegetable",
      "weight": "1kg",
      "price": "45.00 TL",
      "expiry": "N/A",
    },
    {
      "name": "Rice Cakes",
      "brand": "Generic",
      "variant": "Snack",
      "weight": "100g",
      "price": "45.00 TL",
      "expiry": "2026-12-01",
    },
    {
      "name": "Rich Tea",
      "brand": "McVitie's",
      "variant": "Biscuit",
      "weight": "300g",
      "price": "55.00 TL",
      "expiry": "2027-03-15",
    },
    {
      "name": "Schweppes",
      "brand": "Schweppes",
      "variant": "Soda",
      "weight": "1LT",
      "price": "55.00 TL",
      "expiry": "2027-04-10",
    },
    {
      "name": "Spinach Vegetable",
      "brand": "Produce",
      "variant": "Vegetable",
      "weight": "1kg",
      "price": "65.00 TL",
      "expiry": "N/A",
    },
    {
      "name": "Sprite",
      "brand": "Sprite",
      "variant": "Soda",
      "weight": "1LT",
      "price": "45.00 TL",
      "expiry": "2027-02-15",
    },
    {
      "name": "Sprite Lemon-Lime",
      "brand": "Sprite",
      "variant": "Soda",
      "weight": "330ml",
      "price": "28.00 TL",
      "expiry": "2027-02-15",
    },
    {
      "name": "Sultani",
      "brand": "Ülker",
      "variant": "Biscuit",
      "weight": "170g",
      "price": "35.00 TL",
      "expiry": "2026-11-20",
    },
    {
      "name": "Sultani (Grape & Bran)",
      "brand": "Ülker",
      "variant": "Biscuit",
      "weight": "170g",
      "price": "35.00 TL",
      "expiry": "2026-11-20",
    },
    {
      "name": "Tac Bakliyat",
      "brand": "Tac",
      "variant": "Legume",
      "weight": "1kg",
      "price": "85.00 TL",
      "expiry": "2027-10-01",
    },
    {
      "name": "Tartini Frambuazli",
      "brand": "Ülker",
      "variant": "Bakery",
      "weight": "180g",
      "price": "55.00 TL",
      "expiry": "2026-08-30",
    },
    {
      "name": "Tat Bezelye (Peas)",
      "brand": "Tat",
      "variant": "Canned",
      "weight": "800g",
      "price": "65.00 TL",
      "expiry": "2028-02-20",
    },
    {
      "name": "Tat Fasulye (Beans)",
      "brand": "Tat",
      "variant": "Canned",
      "weight": "800g",
      "price": "65.00 TL",
      "expiry": "2028-02-20",
    },
    {
      "name": "Ton Baliği (Light)",
      "brand": "Dardanel",
      "variant": "Tuna",
      "weight": "160g",
      "price": "95.00 TL",
      "expiry": "2028-05-10",
    },
    {
      "name": "Ton Baliği (Olive Oil)",
      "brand": "Dardanel",
      "variant": "Tuna",
      "weight": "160g",
      "price": "110.00 TL",
      "expiry": "2028-05-10",
    },
    {
      "name": "Ton Baliği (Pouch)",
      "brand": "Dardanel",
      "variant": "Tuna",
      "weight": "80g",
      "price": "65.00 TL",
      "expiry": "2028-05-10",
    },
    {
      "name": "Ton Baliği (Spicy)",
      "brand": "Dardanel",
      "variant": "Tuna",
      "weight": "160g",
      "price": "95.00 TL",
      "expiry": "2028-05-10",
    },
    {
      "name": "Ton Baliği (in Oil)",
      "brand": "Dardanel",
      "variant": "Tuna",
      "weight": "160g",
      "price": "85.00 TL",
      "expiry": "2028-05-10",
    },
    {
      "name": "Tukaş Barbunya Pilaki (Borlotti Beans in Olive Oil)",
      "brand": "Tukaş",
      "variant": "Canned",
      "weight": "400g",
      "price": "65.00 TL",
      "expiry": "2028-03-10",
    },
    {
      "name": "Tukaş Misir Konservesi (Canned Corn)",
      "brand": "Tukaş",
      "variant": "Canned",
      "weight": "340g",
      "price": "45.00 TL",
      "expiry": "2028-03-10",
    },
    {
      "name": "Uludağ Meyveli Maden Suyu (Pomegranate/Mixed Fruit)",
      "brand": "Uludağ",
      "variant": "Mineral Water",
      "weight": "200ml",
      "price": "22.00 TL",
      "expiry": "2027-05-15",
    },
    {
      "name": "Uludağ Frutti Karpuz-Çilek (Strawberry-Watermelon)",
      "brand": "Uludağ",
      "variant": "Mineral Water",
      "weight": "200ml",
      "price": "22.00 TL",
      "expiry": "2027-05-15",
    },
    {
      "name": "Uludağ Frutti Limon",
      "brand": "Uludağ",
      "variant": "Mineral Water",
      "weight": "200ml",
      "price": "22.00 TL",
      "expiry": "2027-05-15",
    },
    {
      "name": "Uludağ Frutti Nar (Pomegranate)",
      "brand": "Uludağ",
      "variant": "Mineral Water",
      "weight": "200ml",
      "price": "22.00 TL",
      "expiry": "2027-05-15",
    },
    {
      "name": "Uludağ Gazoz (Large Bottle)",
      "brand": "Uludağ",
      "variant": "Soda",
      "weight": "1.5LT",
      "price": "55.00 TL",
      "expiry": "2027-05-15",
    },
    {
      "name": "Uludağ Portakalli (Orange)",
      "brand": "Uludağ",
      "variant": "Soda",
      "weight": "1.5LT",
      "price": "55.00 TL",
      "expiry": "2027-05-15",
    },
    {
      "name": "VILICIN BALM",
      "brand": "Vilicin",
      "variant": "Balm",
      "weight": "50g",
      "price": "125.00 TL",
      "expiry": "2028-10-01",
    },
    {
      "name": "Vaseline Coco Butter",
      "brand": "Vaseline",
      "variant": "Lotion",
      "weight": "400ml",
      "price": "230.00 TL",
      "expiry": "2028-02-15",
    },
    {
      "name": "Vaseline Kakao Isiltisi",
      "brand": "Vaseline",
      "variant": "Lotion",
      "weight": "400ml",
      "price": "230.00 TL",
      "expiry": "2028-02-15",
    },
    {
      "name": "Vişne (Sour Cherry)",
      "brand": "Produce",
      "variant": "Fruit",
      "weight": "1kg",
      "price": "120.00 TL",
      "expiry": "N/A",
    },
    {
      "name": "WILKINSON Beard & Softener",
      "brand": "Wilkinson",
      "variant": "Grooming",
      "weight": "100ml",
      "price": "350.00 TL",
      "expiry": "2028-06-01",
    },
    {
      "name": "Weetabix Original",
      "brand": "Weetabix",
      "variant": "Cereal",
      "weight": "430g",
      "price": "185.00 TL",
      "expiry": "2027-09-10",
    },
    {
      "name": "Wheat Biscuit",
      "brand": "Generic",
      "variant": "Biscuit",
      "weight": "250g",
      "price": "45.00 TL",
      "expiry": "2027-01-10",
    },
    {
      "name": "White Mushrooms",
      "brand": "Produce",
      "variant": "Vegetable",
      "weight": "400g",
      "price": "55.00 TL",
      "expiry": "N/A",
    },
    {
      "name": "Yedigün Portakal (Orange)",
      "brand": "Yedigün",
      "variant": "Soda",
      "weight": "1LT",
      "price": "42.00 TL",
      "expiry": "2027-04-15",
    },
    {
      "name": "Yellow Apples",
      "brand": "Produce",
      "variant": "Fruit",
      "weight": "1kg",
      "price": "55.00 TL",
      "expiry": "N/A",
    },
    {
      "name": "Yellow Bell Peppers",
      "brand": "Produce",
      "variant": "Vegetable",
      "weight": "500g",
      "price": "65.00 TL",
      "expiry": "N/A",
    },
    {
      "name": "Yesilirmak Su",
      "brand": "Yeşilirmak",
      "variant": "Water",
      "weight": "500ml",
      "price": "20.00 TL",
      "expiry": "2026-08-01",
    },
    {
      "name": "Yonca Sunflower Oil",
      "brand": "Yonca",
      "variant": "Oil",
      "weight": "1LT",
      "price": "92.00 TL",
      "expiry": "2027-10-15",
    },
    {
      "name": "Yudum Sunflower Oil",
      "brand": "Yudum",
      "variant": "Oil",
      "weight": "1LT",
      "price": "98.00 TL",
      "expiry": "2027-11-20",
    },
    {
      "name": "Zucchini",
      "brand": "Produce",
      "variant": "Vegetable",
      "weight": "1kg",
      "price": "45.00 TL",
      "expiry": "N/A",
    },
    {
      "name": "Zwergenwiese / Crackers",
      "brand": "Zwergenwiese",
      "variant": "Cracker",
      "weight": "150g",
      "price": "145.00 TL",
      "expiry": "2026-11-01",
    },
    {
      "name": "white eggplant",
      "brand": "Produce",
      "variant": "Vegetable",
      "weight": "1kg",
      "price": "60.00 TL",
      "expiry": "N/A",
    },
    {
      "name": "Ülker Biscuits",
      "brand": "Ülker",
      "variant": "Biscuit",
      "weight": "150g",
      "price": "35.00 TL",
      "expiry": "2026-11-20",
    },
    {
      "name": "Ülker Lokumcuk (Fruit Flavored Soft Candy)",
      "brand": "Ülker",
      "variant": "Candy",
      "weight": "350g",
      "price": "75.00 TL",
      "expiry": "2027-08-10",
    },
    {
      "name": "Ülker Milk Chocolate Coated Biscuit",
      "brand": "Ülker",
      "variant": "Biscuit",
      "weight": "100g",
      "price": "45.00 TL",
      "expiry": "2026-12-15",
    },
    {
      "name": "Ülker Prens biscuits",
      "brand": "Ülker",
      "variant": "Biscuit",
      "weight": "300g",
      "price": "65.00 TL",
      "expiry": "2026-12-15",
    },
    {
      "name": "Ülker Çikolop (Marshmallow Biscuit)",
      "brand": "Ülker",
      "variant": "Biscuit",
      "weight": "30g",
      "price": "22.00 TL",
      "expiry": "2026-06-30",
    },
    {
      "name": "Ülker Çokonat (Wafer with Hazelnut)",
      "brand": "Ülker",
      "variant": "Wafer",
      "weight": "33g",
      "price": "25.00 TL",
      "expiry": "2026-12-15",
    },
    {
      "name": "Şölen Luppo Sandviç Kek (Cocoa)",
      "brand": "Şölen",
      "variant": "Cake",
      "weight": "184g",
      "price": "75.00 TL",
      "expiry": "2026-09-10",
    },
    {
      "name": "1LT Yudum Sunflower Oil",
      "brand": "Yudum",
      "variant": "Oil",
      "weight": "1LT",
      "price": "98.00 TL",
      "expiry": "2027-11-20",
    },
    {
      "name": "Evvel Sunflower Oil",
      "brand": "Evvel",
      "variant": "Oil",
      "weight": "1LT",
      "price": "95.00 TL",
      "expiry": "2027-05-12",
    },
    {
      "name": "Cappy Pink Grapefruit",
      "brand": "Cappy",
      "variant": "Juice",
      "weight": "1LT",
      "price": "52.00 TL",
      "expiry": "2027-02-25",
    },
    {
      "name": "Tukaş Misir Konservesi (Canned Corn)",
      "brand": "Tukaş",
      "variant": "Canned",
      "weight": "340g",
      "price": "45.00 TL",
      "expiry": "2028-03-10",
    },
  ];

  /// Get attributes by product name
  static Map<String, dynamic>? getByName(String name) {
    if (name == 'Unknown' || name.isEmpty) return null;

    // Normalize Turkish characters to ensure matches between labels.txt and data
    String normalize(String s) {
      return s
          .toLowerCase()
          .replaceAll('ğ', 'g')
          .replaceAll('ü', 'u')
          .replaceAll('ş', 's')
          .replaceAll('ı', 'i')
          .replaceAll('ö', 'o')
          .replaceAll('ç', 'c');
    }

    final searchKey = normalize(name);

    // Checks if the normalized detected label is contained within the normalized product name
    final result = attributes.where(
      (item) => normalize(item["name"].toString()).contains(searchKey),
    );
    return result.isEmpty ? null : result.first;
  }

  /// Get attributes by brand
  static List<Map<String, dynamic>> getByBrand(String brand) {
    return attributes.where((item) => item["brand"] == brand).toList();
  }
}
